version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    hostname: postgres
    user: root
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
